### ISSUE TITLE
Possible carry flag bug with subtract in Ben emulator?

### ISSUE THREAD

**Issue by Hotwire75** [Naheel-Azawy/Basic-Computer-Emulator#2]
Not really sure about this as I am way over my head here, but I tried running the multiplication code at https://youtu.be/Zg1NdPKoosU?t=40m11s and had no luck with it... 

From what I understand listening to the video, when subtracting 1 it should always set the carry flag when not subtracting from zero, but the CF register is always zero, so the JC 0006 command is passed by and it goes straight through to the HLT.

Attached is the program in binary where I tried to multiply 4 by 5.

[ben-multiply.bin.txt](https://github.com/Naheel-Azawy/Simple-Computer-Simulator/files/2216584/ben-multiply.bin.txt)

**Comment by Naheel-Azawy** [comment]
Thanks, fixed!
